blank_issues_enabled: false
contact_links:
  - name: Feedback (Use Cases / Questions)
    url: https://github.com/aRcHmaGe333/udf/issues/new?template=feedback.yml
    about: Share use cases, unclear parts, or scenarios we should measure.

